language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saurabh333/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saurabh333/react-test npm run test

after_success:
  - docker build -t saurabh333/multi-container-client ./client
  - docker build -t saurabh333/multi-container-nginx ./nginx
  - docker build -t saurabh333/multi-container-server ./server
  - docker build -t saurabh333/multi-container-worker ./worker
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all the images to Docker hub
  - docker push saurabh333/multi-container-client
  - docker push saurabh333/multi-container-nginx
  - docker push saurabh333/multi-container-server
  - docker push saurabh333/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-container-app'
  env: 'Multicontainerapp-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-313447773450'
  bucket_path: 'multi-container'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY